export const PROF_CONFIG = {
  buttons: {
    addProfessional: 'Agregar profesional',
  },
  filter: {
    title: 'Filtrar',
  },
  search: {
    placeholder: 'Buscar profesional',
  },
  table: {
    title: 'Listado de Profesionales',
    headers: ['Nombre', 'Área', 'Espec.', 'Disp.', 'Acciones'],
    noResults: 'No hay resultados',
  },
};

export const PROF_CREATE_CONFIG = {
  title: 'Crear un nuevo profesional',
  formTitle: 'Formulario de creación',
  formDescription: 'Ingresá los datos para dar de alta a un nuevo profesional',
  buttons: {
    cancel: 'Cancelar',
    create: 'Crear profesional',
  },
  breadcrumb: [
    { id: 1, name: 'Inicio', path: '/' },
    { id: 2, name: 'Profesionales', path: '/professionals' },
    { id: 3, name: 'Crear', path: '/create' },
  ],
  labels: {
    area: 'Área',
    available: 'Disponible',
    email: 'Correo electrónico',
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    specialization: 'Especialidad',
    titleAbbreviation: 'Título',
  },
  placeholders: {
    area: 'Ingresá el área',
    email: 'Ingresá el correo electrónico',
    firstName: 'Ingresá el nombre',
    lastName: 'Ingresá el apellido',
    phone: 'Ingresá el teléfono',
    specialization: 'Ingresá la especialidad',
    titleAbbreviation: 'Ingresá el título',
  },
};

// export const professionals: IProfessional[] = [
//   {
//     area: 'Medicina',
//     email: 'juan.perez@gmail.com',
//     firstName: 'Juan',
//     id: 1,
//     lastName: 'Pérez',
//     specialization: 'Cardiología',
//     titleAbbreviation: 'Dr.',
//   },
//   {
//     area: 'Medicina',
//     email: 'maria.gomez@gmail.com',
//     firstName: 'María',
//     id: 2,
//     lastName: 'Gómez',
//     specialization: 'Dermatología',
//     titleAbbreviation: 'Dra.',
//   },
//   {
//     area: 'Medicina',
//     email: 'carlos.lopez@gmail.com',
//     firstName: 'Carlos',
//     id: 3,
//     lastName: 'López',
//     specialization: 'Pediatría',
//     titleAbbreviation: 'Dr.',
//   },
//   {
//     area: 'Medicina',
//     email: 'ana.martinez@gmail.com',
//     firstName: 'Ana',
//     id: 4,
//     lastName: 'Martínez',
//     specialization: 'Neurología',
//     titleAbbreviation: 'Dra.',
//   },
//   {
//     area: 'Medicina',
//     email: 'luisa.rodriguez@gmail.com',
//     firstName: 'Luisa',
//     id: 5,
//     lastName: 'Rodríguez',
//     specialization: 'Ginecología',
//     titleAbbreviation: 'Dra.',
//   },
//   {
//     area: 'Medicina',
//     email: 'juan.perez@gmail.com',
//     firstName: 'Juan',
//     id: 6,
//     lastName: 'Pérez',
//     specialization: 'Cardiología',
//     titleAbbreviation: 'Dr.',
//   },
//   {
//     area: 'Medicina',
//     email: 'maria.gomez@gmail.com',
//     firstName: 'María',
//     id: 7,
//     lastName: 'Gómez',
//     specialization: 'Dermatología',
//     titleAbbreviation: 'Dra.',
//   },
//   {
//     area: 'Medicina',
//     email: 'carlos.lopez@gmail.com',
//     firstName: 'Carlos',
//     id: 8,
//     lastName: 'López',
//     specialization: 'Pediatría',
//     titleAbbreviation: 'Dr.',
//   },
//   {
//     area: 'Medicina',
//     email: 'ana.martinez@gmail.com',
//     firstName: 'Ana',
//     id: 9,
//     lastName: 'Martínez',
//     specialization: 'Neurología',
//     titleAbbreviation: 'Dra.',
//   },
//   {
//     area: 'Medicina',
//     email: 'luisa.rodriguez@gmail.com',
//     firstName: 'Luisa',
//     id: 10,
//     lastName: 'Rodríguez',
//     specialization: 'Ginecología',
//     titleAbbreviation: 'Dra.',
//   },
// ];
