export const PROF_SCHEMA = {
  areaMessage: 'Debes seleccionar un área',
  availableMessage: 'Debes seleccionar una disponibilidad',
  descriptionMessage: 'Debes ingresar una descripción',
  dniMessage: 'Debes ingresar un DNI',
  emailMessage: 'Debes ingresar un e-mail válido',
  firstNameMessage: 'Debes ingresar un nombre',
  lastNameMessage: 'Debes ingresar un apellido',
  phoneMessage: 'Debes ingresar un número de teléfono',
  scheduleTimeInitMessage: 'Debes ingresar una hora de inicio',
  scheduleTimeInitRangeMessage: 'Hora de 00 a 23 y minutos de 00 a 59',
  scheduleTimeEndMessage: 'Debes ingresar una hora de fin',
  slotDurationMessage: 'Debes ingresar la duración de los turnos',
  specializationMessage: 'Debes seleccionar una especialización',
  timeSlotUnavailableInitMessage: 'Debes ingresar una hora de inicio',
  timeSlotUnavailableEndMessage: 'Debes ingresar una hora de fin',
  titleAbbreviationMessage: 'Debes ingresar una abreviación de título',
  workingDaysMessage: 'Debes seleccionar al menos un día laboral',
};
