export const PROF_UPDATE_CONFIG = {
  title: 'Actualizar un profesional',
  formTitle: 'Formulario de actualización',
  formDescription: 'Modificá los datos para actualizar a un profesional',
  buttons: {
    cancel: 'Cancelar',
    create: 'Actualizar profesional',
  },
  breadcrumb: [
    { id: 1, name: 'Inicio', path: '/' },
    { id: 2, name: 'Profesionales', path: '/professionals' },
    { id: 3, name: 'Actualizar', path: '/update' },
  ],
  labels: {
    area: 'Área',
    available: 'Disponible',
    email: 'Correo electrónico',
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    scheduleTimeInit: 'Inicio de turnos',
    scheduleTimeEnd: 'Fin de turnos',
    specialization: 'Especialidad',
    timeSlotUnavailableInit: 'Inicio de descanso',
    timeSlotUnavailableEnd: 'Fin de descanso',
    titleAbbreviation: 'Título',
  },
  placeholders: {
    area: 'Ingresá el área',
    email: 'Ingresá el correo electrónico',
    firstName: 'Ingresá el nombre',
    lastName: 'Ingresá el apellido',
    phone: 'Ingresá el teléfono',
    scheduleTimeInit: 'Ingresá la hora de inicio',
    scheduleTimeEnd: 'Ingresá la hora de finalización',
    timeSlotUnavailableInit: 'Ingresá la hora de inicio',
    timeSlotUnavailableEnd: 'Ingresá la hora de finalización',
    specialization: 'Ingresá la especialidad',
    titleAbbreviation: 'Ingresá el título',
  },
};